# Generated by Django 5.0.6 on 2024-08-18 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_quizmaster', '0002_alter_quiz_date_to_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='date_to_start',
            field=models.DateTimeField(),
        ),
    ]
