# Generated by Django 5.0.6 on 2024-08-23 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_quizmaster', '0006_alter_question_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.CharField(blank=True, default='-', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='option1',
            field=models.CharField(blank=True, default='-', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='option2',
            field=models.CharField(blank=True, default='-', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='option3',
            field=models.CharField(blank=True, default='-', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='option4',
            field=models.CharField(blank=True, default='-', max_length=500),
            preserve_default=False,
        ),
    ]
